name: workflow-test

on: 
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
  
  with:
    php-version: '8.1'
    tools: php-cs-fixer, phpunit

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/phpunit@v3
